# This is a basic workflow to help you get started with Actions

name: Greeting from Ng Wing Ki Vickie

# Controls when the action will run. 
on: push


jobs:
  my-job: 
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Wing Ki
        MIDDLE_NAME: Vickie
        LAST_NAME: Ng
      run:
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
